#!/bin/bash
source /boot/config/plugins/openvpnserver/openvpnserver_cert.cfg
if [[ "$DISCONNECT_ON_UMOUNT" == "yes" ]]; then
	logger "Stopping OpenVPN Server"
	/usr/local/emhttp/plugins/openvpnserver/scripts/rc.openvpnserver stop | logger
fi